# Workflow para CD (ações para deploy do produto)
name: 'CD: Main Workflow'

env:
  VERCEL_TOKEN: '${{ secrets.VERCEL_TOKEN }}'
  VERCEL_ORG_ID: '${{ secrets.VERCEL_ORG_ID }}'
  VERCEL_PROJECT_ID: '${{ secrets.VERCEL_PROJECT_ID }}'

on:
  push:
    branches: [main, cd-vercel]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Install
        run: npm install
      - name: Run Deploy
        run: npm run deploy:prod