name: 'CI: Main Workflow'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      # First install this project
      - name: Run Installation
        run: npm install
      - name: Apply Linter
        run: npm run lint